version: '3'
services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - "./nginx/config/block.conf:/etc/nginx/block.conf"
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - honeypot
      - shop
      - fail2ban

  shop:
    image: shop_image
    container_name: shop
    build:
      context: ./shop/docker
    networks:
      - mynetwork

  honeypot:
    image: honeypot_image
    container_name: honeypot
    build:
      context: ./honeypot/docker
    networks:
      - mynetwork

  fail2ban:
    build:
      context: ./fail2ban/docker
    container_name: fail2ban
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/nginx:/var/log/nginx
      - "./logs/fail2ban:/var/log/fail2ban"
      - "./fail2ban/config:/data"
      - "/var/lib/docker/containers/:/container-logs/:ro"
      - "./nginx/config/block.conf:/etc/nginx/block.conf"
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf"
    env_file:
      - "./fail2ban.env"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    networks:
      - mynetwork

networks:
  mynetwork:
